### ISSUE TITLE
Forms in repo are for 2021

### ISSUE THREAD

**Issue by amarder** [datcsv/tez-tax#15]
I'm working on my 2022 taxes, it looks like the forms in the repo need to be updated. Any tips on how one might do that?
Thanks for sharing this awesome project!

**Comment by datcsv** [comment]
Good catch, I didn't even consider those may have changed. I will try to update today or tomorrow. Thank you!

**Comment by datcsv** [comment]
@amarder Updated, thank you! https://github.com/datcsv/tez-tax/commit/a710c9a3c9a95dcb37503c8dbbd78321c9af5ebf

**Comment by amarder** [comment]
Awesome, thank you!!

**Comment by datcsv** [comment]
@amarder I apologize - there was a slight change in the Schedule 1 form that I need to compensate for. Will update within the next few minutes and push. Sorry!

**Comment by datcsv** [comment]
@amarder Fixed again, sorry! https://github.com/datcsv/tez-tax/commit/5153649cf1f24ff63a6242046344143481ae9cb1

**Comment by amarder** [comment]
Nice! My tezos income was a whopping $4.28 so wasn't running into this issue.
